/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AeProForm: typeof import('./src/components/modules/AeProForm.vue')['default']
    ArithmeticCaptcha: typeof import('./src/components/public/ArithmeticCaptcha.vue')['default']
    AutocompleteArray: typeof import('./src/components/pro-crud/AutocompleteArray.vue')['default']
    BaseChart: typeof import('./src/components/public/BaseChart.vue')['default']
    DashboardHeader: typeof import('./src/components/modules/layout/DashboardHeader.vue')['default']
    DashboardLayout: typeof import('./src/components/modules/layout/DashboardLayout.vue')['default']
    HikMsePlayer: typeof import('./src/components/modules/dashboard-main/monitor-video/monitor-tools/comps/HikMsePlayer.vue')['default']
    HlsPlayer: typeof import('./src/components/modules/dashboard-main/monitor-video/monitor-tools/comps/HlsPlayer.vue')['default']
    IEpClose: typeof import('~icons/ep/close')['default']
    IEpRight: typeof import('~icons/ep/right')['default']
    IEpSwitch: typeof import('~icons/ep/switch')['default']
    JoystickPanel: typeof import('./src/components/modules/dashboard-main/monitor-video/monitor-tools/comps/JoystickPanel.vue')['default']
    LibreMap: typeof import('./src/components/modules/dashboard-main/data-board/maplibre/LibreMap.vue')['default']
    MonitorPlayBack: typeof import('./src/components/modules/dashboard-main/monitor-video/monitor-tools/func-tabs/MonitorPlayBack.vue')['default']
    MonitorPlayer: typeof import('./src/components/modules/dashboard-main/monitor-video/monitor-tools/MonitorPlayer.vue')['default']
    MonitorPreview: typeof import('./src/components/modules/dashboard-main/monitor-video/monitor-tools/func-tabs/MonitorPreview.vue')['default']
    NavMultiTabs: typeof import('./src/components/modules/NavMultiTabs.vue')['default']
    PanTilt: typeof import('./src/components/modules/dashboard-main/monitor-video/monitor-tools/comps/PanTilt.vue')['default']
    PreviewMonitorVideo: typeof import('./src/components/modules/dashboard-main/monitor-video/monitor-tools/comps/PreviewMonitorVideo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchMenuRight: typeof import('./src/components/pro-crud/SearchMenuRight.vue')['default']
    SiteVideoTree: typeof import('./src/components/modules/dashboard-main/monitor-video/monitor-tools/comps/SiteVideoTree.vue')['default']
    TestMonitorPage: typeof import('./src/components/modules/dashboard-main/monitor-video/monitor-tools/TestMonitorPage.vue')['default']
    TestTabComp: typeof import('./src/components/modules/dashboard-main/monitor-video/monitor-tools/TestTabComp.vue')['default']
    TimeLine: typeof import('./src/components/modules/dashboard-main/monitor-video/monitor-tools/comps/TimeLine/TimeLine.vue')['default']
    TimeSegment: typeof import('./src/components/modules/dashboard-main/monitor-video/monitor-tools/comps/TimeSegment.vue')['default']
    UserPopperAvatar: typeof import('./src/components/modules/layout/UserPopperAvatar.vue')['default']
    WindowListItem: typeof import('./src/components/modules/dashboard-main/monitor-video/monitor-tools/comps/TimeLine/WindowListItem.vue')['default']
  }
}
