/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AeProForm: typeof import('./src/components/modules/AeProForm.vue')['default']
    ArithmeticCaptcha: typeof import('./src/components/public/ArithmeticCaptcha.vue')['default']
    AutocompleteArray: typeof import('./src/components/pro-crud/AutocompleteArray.vue')['default']
    DashboardHeader: typeof import('./src/components/modules/dashboard/DashboardHeader.vue')['default']
    DashboardLayout: typeof import('./src/components/modules/dashboard/DashboardLayout.vue')['default']
    NavMultiTabs: typeof import('./src/components/modules/NavMultiTabs.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchMenuRight: typeof import('./src/components/pro-crud/SearchMenuRight.vue')['default']
    UserPopperAvatar: typeof import('./src/components/modules/dashboard/UserPopperAvatar.vue')['default']
  }
}
