/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    'dashboard-main': RouteRecordInfo<
      'dashboard-main',
      '/modules/dashboard-main',
      Record<never, never>,
      Record<never, never>,
      | '/modules/dashboard-main/data-board'
      | '/modules/dashboard-main/monitor-video'
    >,
    '/modules/dashboard-main/data-board': RouteRecordInfo<
      '/modules/dashboard-main/data-board',
      '/modules/dashboard-main/data-board',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/modules/dashboard-main/monitor-video': RouteRecordInfo<
      '/modules/dashboard-main/monitor-video',
      '/modules/dashboard-main/monitor-video',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'project-settings': RouteRecordInfo<
      'project-settings',
      '/modules/project-settings',
      Record<never, never>,
      Record<never, never>,
      | '/modules/project-settings/base-infos'
      | '/modules/project-settings/base-infos/hydropower-station'
      | '/modules/project-settings/base-infos/user-message'
      | '/modules/project-settings/monitoring-configuration'
      | 'account-info'
      | 'account-settings'
      | 'workbench'
    >,
    'account-settings': RouteRecordInfo<
      'account-settings',
      '/modules/project-settings/account-settings',
      Record<never, never>,
      Record<never, never>,
      | 'account-info'
    >,
    'account-info': RouteRecordInfo<
      'account-info',
      '/modules/project-settings/account-settings/account-info',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/modules/project-settings/base-infos': RouteRecordInfo<
      '/modules/project-settings/base-infos',
      '/modules/project-settings/base-infos',
      Record<never, never>,
      Record<never, never>,
      | '/modules/project-settings/base-infos/hydropower-station'
      | '/modules/project-settings/base-infos/user-message'
    >,
    '/modules/project-settings/base-infos/hydropower-station': RouteRecordInfo<
      '/modules/project-settings/base-infos/hydropower-station',
      '/modules/project-settings/base-infos/hydropower-station',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/modules/project-settings/base-infos/user-message': RouteRecordInfo<
      '/modules/project-settings/base-infos/user-message',
      '/modules/project-settings/base-infos/user-message',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/modules/project-settings/monitoring-configuration': RouteRecordInfo<
      '/modules/project-settings/monitoring-configuration',
      '/modules/project-settings/monitoring-configuration',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'workbench': RouteRecordInfo<
      'workbench',
      '/modules/project-settings/workbench',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'system-settings': RouteRecordInfo<
      'system-settings',
      '/modules/system-settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '404': RouteRecordInfo<
      '404',
      '/public/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'login': RouteRecordInfo<
      'login',
      '/public/login-page',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/test-page': RouteRecordInfo<
      '/test-page',
      '/test-page',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
    'src/pages/modules/dashboard-main.vue': {
      routes:
        | '/modules/dashboard-main/data-board'
        | '/modules/dashboard-main/monitor-video'
        | 'dashboard-main'
      views:
        | 'default'
    }
    'src/pages/modules/dashboard-main/data-board.vue': {
      routes:
        | '/modules/dashboard-main/data-board'
      views:
        | never
    }
    'src/pages/modules/dashboard-main/monitor-video.vue': {
      routes:
        | '/modules/dashboard-main/monitor-video'
      views:
        | never
    }
    'src/pages/modules/project-settings.vue': {
      routes:
        | '/modules/project-settings/base-infos'
        | '/modules/project-settings/base-infos/hydropower-station'
        | '/modules/project-settings/base-infos/user-message'
        | '/modules/project-settings/monitoring-configuration'
        | 'account-info'
        | 'account-settings'
        | 'project-settings'
        | 'workbench'
      views:
        | 'default'
    }
    'src/pages/modules/project-settings/account-settings.vue': {
      routes:
        | 'account-info'
        | 'account-settings'
      views:
        | 'default'
    }
    'src/pages/modules/project-settings/account-settings/account-info.vue': {
      routes:
        | 'account-info'
      views:
        | never
    }
    'src/pages/modules/project-settings/base-infos.vue': {
      routes:
        | '/modules/project-settings/base-infos'
        | '/modules/project-settings/base-infos/hydropower-station'
        | '/modules/project-settings/base-infos/user-message'
      views:
        | 'default'
    }
    'src/pages/modules/project-settings/base-infos/hydropower-station.vue': {
      routes:
        | '/modules/project-settings/base-infos/hydropower-station'
      views:
        | never
    }
    'src/pages/modules/project-settings/base-infos/user-message.vue': {
      routes:
        | '/modules/project-settings/base-infos/user-message'
      views:
        | never
    }
    'src/pages/modules/project-settings/monitoring-configuration.vue': {
      routes:
        | '/modules/project-settings/monitoring-configuration'
      views:
        | never
    }
    'src/pages/modules/project-settings/workbench.vue': {
      routes:
        | 'workbench'
      views:
        | never
    }
    'src/pages/modules/system-settings/index.vue': {
      routes:
        | 'system-settings'
      views:
        | never
    }
    'src/pages/public/404.vue': {
      routes:
        | '404'
      views:
        | never
    }
    'src/pages/public/login-page.vue': {
      routes:
        | 'login'
      views:
        | never
    }
    'src/pages/test-page.vue': {
      routes:
        | '/test-page'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
